version: "3.7"
services:

  roscore:
    build:
      context: ./roscore
    networks:
      - ros-custom
    ports:
      - "9090:9090"
    environment:
      - ROS_MASTER_URI=http://roscore:11311
    container_name: roscore
    tty: true

  parser:
    build:
      context: ./pose_parser
    networks:
      - ros-custom
    ports:
      - "9999:9999"
    environment:
      - ROS_MASTER_URI=http://roscore:11311
      - DISPLAY=novnc:0.0
    tty: true
    depends_on:
      - roscore

#  simulator:
#    build:
#      context: ./simulator
#    networks:
#      - ros-custom
#    ports:
#      - "9091:9091"
#    environment:
#      - DISPLAY=novnc:0.0
#      - ROS_MASTER_URI=http://roscore:11311
#    tty: true
#    depends_on:
#      - roscore
#      - novnc

  posenet:
    build:
      context: ./posenet
    networks:
      - ros-custom
    ports:
      - "8888:443"
      - "8889:443"
      - "5000:5000"
    environment:
      - ROS_MASTER_URI=http://roscore:11311
    tty: true
    depends_on:
      - roscore

  novnc:
    container_name: novnc
    image: theasp/novnc
    networks:
      ros-custom:
    ports:
      - "8080:8080"
    tty: true

networks:
  ros-custom:
    name: ros-custom
    driver: bridge
