version: "3.7"
services:
#  openpose:
#    build:
#      context: ./openpose-melodic-ros
#    networks:
#      - ros-custom
#    ports:
#      - "9090:9090"

  roscore:
    build:
      context: ./roscore
    networks:
      - ros-custom
    ports:
      - "9090:9090"
    container_name: roscore
    tty: true

  simulator:
    build:
      context: ./simulator
    networks:
      - ros-custom
    ports:
      - "9091:9091"
    environment:
      - OS_MASTER_URI=http://roscore:9090
    tty: true
    depends_on:
      - roscore

  posenet:
    build:
      context: ./posenet
    networks:
      - ros-custom
    ports:
      - "8888:80"
      - "8889:443"
    environment:
      - OS_MASTER_URI=http://roscore:9090
    tty: true
    depends_on:
      - roscore

networks:
  ros-custom:
    name: ros-custom
    driver: bridge
