version: "3.6"
services:
  openpose:
    build:
      context: ./openpose-melodic-ros
      networks:
        - ros-custom
#      container_name: posedetect

#  imagedetect:
#    build:
#      context: ./camera
#      networks:
#        - ros-custom
#      container_name: imagedetect
#      ports:
#        - "9091:9090"

#  drone:
#    build:
#      context: ./drone
#      networks:
#        - ros-custom
#      container_name: drone
#      ports:
#      - "9092:9090"

