version: "3.6"
services:
  imagedetect:
    context: ./camera
    network: ros-custom
    container_name: imagedetect
    ports:
      - "9091:9090"

#  drone:
#    context: ./drone
#    network: ros-custom
#    container_name: drone
#    ports:
#    - "9092:9090"

