version: "3.7"
services:
#  openpose:
#    build:
#      context: ./openpose-melodic-ros
#    networks:
#      - ros-custom
#    ports:
#      - "9090:9090"

  posenet:
    build:
      context: ./posenet
    networks:
      - ros-custom
    ports:
      - "9091:9090"
      - "9090:80"
    environment:
      - OS_MASTER_URI=http://roscore:9090

  roscore:
    build:
      context: ./roscore
    networks:
      - ros-custom
    ports:
      - "9090"
    container_name: roscore


networks:
  ros-custom:
    name: ros-custom
