version: "3.6"
services:
  imagedetect:
    context: ./posenet
    network: ros-custom
    container_name: imagedetect
    ports:
      - "9091:9090"

#  roscore:
#    context: ./roscore
#    network: ros-custom
#    container_name: roscore
#    ports:
#    - "9092:9090"

