version: "3.7"
services:
  openpose:
    build:
      context: ./openpose-melodic-ros
    networks:
      - ros-custom
    ports:
      - "9090:9090"

#  imagedetect:
#    build:
#      context: ./camera
#    networks:
#      - ros-custom
#    ports:
#      - "9091:9090"

#  drone:
#    build:
#      context: ./drone
#    networks:
#      - ros-custom
#    ports:
#    - "9092:9090"

